### ISSUE TITLE
400 Bad Request

### ISSUE THREAD

**Issue by che1404** [pacification/fastlane-plugin-diawi#11] opened 2020-01-17 12:17 UTC
Hi, thanks for your contribution with this plugin.

We are trying to upload an iOS build to Diawi but it throws a 400 Bad Request error. 
Any clue on how can we fix this?

Thanks.

**Comment by pacification** [comment] 2020-02-20 07:28
Hi, @che1404. Sorry for long delay. Do you still need help?

**Comment by che1404** [comment] 2020-02-20 07:34
Hi, no worries @pacification. Actually we are stuck on the same issue. We are getting a. 400 Bad Request error. 
I got in touch with diawi developers and here are some findings:
- The problem seems to happen on macOS Catalina only. We noticed that when using the diawi API with the Catalina curl distribution, we were getting this error as well
- The files trying to upload were not the problem, since we could upload them just by drag and dropping into the browser.
- We tried the same curl command with --http1.1 option, and it actually worked.
- Then I installed another curl implementation with homebrew, curl-openssl, and the command seemed to worked as well with no --http1.1 option.

Does any of this ring any bell?

**Comment by pacification** [comment] 2020-02-20 10:24
Thanks for response. I'm currently trying to reproduce 400 bad request and i have no success attempts.

If it ok to you to use:

> Then I installed another curl implementation with homebrew, curl-openssl, and the command seemed to worked as well with no --http1.1 option.

then i close the issue, because i believe i have the same setup and all works fine. If not, please try to see/debug [source code](https://github.com/pacification/fastlane-plugin-diawi/blob/v1.4.0/lib/fastlane/plugin/diawi/actions/diawi_action.rb.) for any problems. Thanks.

**Comment by pacification** [comment] 2020-02-20 12:09
@che1404, i also released 2.0.0 version. Feel free to try.

**Closed** 2020-02-24 07:31 UTC

**Comment by abingeorgev** [comment] 2020-02-27 12:11
Am getting the same error in version 2.0.0

**Comment by che1404** [comment] 2020-07-14 16:17
Yep, me too :(

**Comment by abingeorgev** [comment] 2020-08-23 18:54
@che1404 Nope. Still trying different things.
